mqtt:
  server: tcp://192.168.1.99:1883
  host: 192.168.1.99
  base_topic: zigbee2mqtt
  qos_value: 1
  port: 1883

devices:
  '0':
    temperature_sensor: living_room/temp_sensor
    valve_actuator: living_room/thermo_valve
  '1':
    temperature_sensor: kids_bedroom/temp_sensor
    valve_actuator: kids_bedroom/thermo_valve
  '2':
    temperature_sensor: office/temp_sensor
    valve_actuator: office/thermo_valve
  '3':
    temperature_sensor: bathroom/temp_sensor
    valve_actuator: bathroom/thermo_valve
  '4':
    temperature_sensor: master_bedroom/temp_sensor
    valve_actuator: master_bedroom/thermo_valve

